language: csharp
solution: GoogleApi.sln
install:
  - nuget restore GoogleApi.sln
  - nuget install NUnit.ConsoleRunner -Version 3.7.0  -OutputDirectory testing
script:
  - xbuild /p:Configuration=Release GoogleApi.sln
