version: 3.8.0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: Any CPU
force_https_clone: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.myget.org/F/wannasport
  NUGET_APIKEY: 
    secure: yMeWmWdQRq8bMauFYpWoluKNuh/+GOyniRyIKi1xVK9e6pSSx0uDfsiWHM4v9QdN
build_script:
- ps: >-
    dotnet restore;
    dotnet build .\GoogleApi.sln;
deploy_script:
- ps: >-
    dotnet nuget push .\GoogleApi\GoogleApi\Bin\Release\GoogleApi.$VERSION.nupkg -s $env:NUGET_HOST -k $env:NUGET_APIKEY;
