version: 3.8.0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: Any CPU
force_https_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST:  https://api.nuget.org
  NUGET_APIKEY: 
    secure: oeSwT33L7QcWnDXH3H/pWIUJDdM+el24LvqEQ6HqzpR0Ok/7Z3VZj51u14veU1Ho
build_script:
- ps: >-
    dotnet build .\GoogleApi.sln;
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master 